import About from "@/components/About";
import Background from "@/components/Background";
import LandingSection from "@/components/LandingSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Baha Eddine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <Background />
        <LandingSection />
        <About />
      </main>
    </>
  );
}
